version: '3.4'

services:
  api:
    image: "oluwaetosin/libary_api"
    build:
      context: ./
      dockerfile: ./Library.Api/Dockerfile
    volumes:
      - ./dataa:/app/data
    ports:
      -  8084:8080
 